### ISSUE TITLE
Rename binary 'gs'

### ISSUE THREAD

**Issue by jayvdb** [moremoban/gease#2]
'gs' is ghostscript.

Distros will not allow 'gs' to be anything else.

So this needs a new binary name.

**Comment by chfw** [comment]
https://github.com/moremoban/gease/commit/c2bdc6e4be687c4a1729ec12a47a832043fc917d#diff-a4ad8f6c92054b0970b6f4cf5f7754ec5013d7d14f4f67e7cfeddd08c7e92895
